#!/bin/bash
# Copyright (c) 2025 Mihai Stancu (https://github.com/curatorium)

set -Eeuo pipefail;
shopt -s inherit_errexit;
shopt -s nullglob;

REPO="$(git rev-parse --show-toplevel)"

# ShellCheck
for file in steward libs/args libs/inliner; do
  cd "$(dirname "$REPO/$file")";
  shellcheck -x "$REPO/$file" ||
      (echo "ERROR: $file failed shellcheck." && exit 3);
  cd -;
done

# Tests
for file in steward.test libs/args.test; do
  "$REPO/$file" > "$REPO/$file.md" &&
  [[ "$("$REPO/$file")" == "$(cat "$REPO/$file.md")" ]] ||
      (echo "ERROR: $file tests failed." && exit 3);
done

# Docs up to date
[[ "$("$REPO/readme")" == "$(cat "$REPO/README.md")" ]] ||
    (echo "Docs are out of date." && exit 2);
