#!/bin/bash
# Copyright (c) 2025 Mihai Stancu (https://github.com/curatorium)

source /usr/local/bin/bash-import;

DOCFILE="$(dirname ${BASH_SOURCE[0]})/../steward";
export DOCFILE;

T=$'\t'

cat <<-TXT
	NAME
	${T}steward -- $(docs:tag steward desc)

	USAGE
	$(docs:tag -i 1 steward usage)

	$(docs:tag -i 1 steward flag,option,arg)

	SYNTAX
TXT

for name in $(docs:list keyword); do
	cat <<-TXT | awk 'NF{print; blank=0} !NF && !blank++{print ""}'
		$name -- $(docs:tag "$name" desc)

		$(docs:tag -i 1 "$name" usage)

		$(docs:tag -i 1 "$name" flag,option,arg)

	TXT
done | sed 's/^/\t/'

cat <<-TXT

	SCHEDULE
	${T}eager 0-99
	${T}  internal
	${T}    prereqs
	${T}    key
	${T}    src
	${T}    deb
	${T}    apt
	${T}    ext
	${T}    bin
	${T}    tar
	${T}    zip
	${T}    npm
	${T}    composer
	${T}    helm
	${T}    pip
	${T}    go
	${T}    apt-cleanup
	${T}  defer 0-99

TXT

