#!/bin/bash
# Copyright (c) 2025 Mihai Stancu (https://github.com/curatorium)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Raw text documentation extractor functions for bash scripts with @tag annotations.
# Source this file and set DOCFILE to the file to extract documentation from.

DOCFILE="${DOCFILE:-}"

# @name help:names
# @type function
#
# @arg <type>	The @type to filter by (command, keyword, function)
help:names() {
	local type="${1?usage: help:names <type>}"; shift;
	grep -B1 "^# @type $type" "$DOCFILE" | grep -oP '(?<=^# @name )\S+'
}

# @name help:tag
# @type function
#
# @arg <name>	The @name of the documented item
# @arg <tag>	The tag to extract (desc, usage, arg, flag, etc.)
help:tag() {
	local name="${1?usage: help:tag <name> <tag>}"; shift;
	local tag="${1?usage: help:tag <name> <tag>}"; shift;
	sed -n "/^# @name $name\$/,/^# @name /p" "$DOCFILE" | grep "^# @$tag " | sed "s/^# @$tag //"
}

# @name help:header
# @type function
#
# @arg <name>	The @name of the documented item
help:header() {
	local name="${1?usage: help:header <name>}"; shift;
	cat <<-TXT
		NAME
			${name/#/	} -- $(help:desc "$name")

		USAGE
			$(help:usage "$name" | sed 's/^/	/')

			$(help:flag "$name" | sed 's/^/	/')
			$(help:option "$name" | sed 's/^/	/')
			$(help:arg "$name" | sed 's/^/	/')

	TXT
}

# @name help:item
# @type function
#
# @arg <name>	The @name of the documented item
help:item() {
	local name="${1?usage: help:item <name>}"; shift;
	cat <<-TXT | awk 'NF{print; blank=0} !NF && !blank++{print ""}'
		$name -- $(help:desc "$name")

			$(help:usage "$name" | sed 's/^/	/')

			$(help:flag "$name" | sed 's/^/	/')
			$(help:option "$name" | sed 's/^/	/')
			$(help:arg "$name" | sed 's/^/	/')

	TXT
}

# @name help:section
# @type function
#
# @arg <type>	The @type to filter by (command, keyword, function)
help:section() {
	local type="${1?usage: help:section <type>}"; shift;
	for name in $(help:names "$type"); do
		help:item "$name" | sed 's/^/	/'
	done
}

# @name help:desc
# @type function
#
# @arg <name>	The @name of the documented item
help:desc() {
	local name="${1?usage: help:desc <name>}"; shift;
	help:tag "$name" desc
}

# @name help:usage
# @type function
#
# @arg <name>	The @name of the documented item
help:usage() {
	local name="${1?usage: help:usage <name>}"; shift;
	help:tag "$name" usage
}

# @name help:flag
# @type function
#
# @arg <name>	The @name of the documented item
help:flag() {
	local name="${1?usage: help:flag <name>}"; shift;
	help:tag "$name" flag
}

# @name help:option
# @type function
#
# @arg <name>	The @name of the documented item
help:option() {
	local name="${1?usage: help:option <name>}"; shift;
	help:tag "$name" option
}

# @name help:arg
# @type function
#
# @arg <name>	The @name of the documented item
help:arg() {
	local name="${1?usage: help:arg <name>}"; shift;
	help:tag "$name" arg
}
